(()=>{"use strict";
const KEY="moraa_admin_workspace_v1", SESSION="moraa_admin_session_v1";
const START={settings:{businessName:"Moraa Beauty Parlour",tagline:"Beauty, Refined.",heroHeadline:"Beauty, Refined.",heroText:"Where elegance meets exceptional beauty care.",hoursDays:"Monday–Saturday",hoursTime:"9:00 AM–7:00 PM",phone:"",whatsapp:"",email:"",location:"Nairobi, Kenya",about:"Moraa Beauty Parlour is a modern beauty destination where thoughtful service, polished finishing and a calm atmosphere come together."},products:[
{id:"p1",name:"Moraa Signature Shampoo",sku:"MOR-SHAM-01",category:"Hair Care",price:1800,cost:900,stock:12,reorder:4,active:true},
{id:"p2",name:"Nourishing Hair Mask",sku:"MOR-MASK-01",category:"Hair Care",price:2200,cost:1100,stock:8,reorder:3,active:true},
{id:"p3",name:"Luxury Body Oil",sku:"MOR-OIL-01",category:"Body Care",price:2500,cost:1250,stock:15,reorder:5,active:true},
{id:"p4",name:"Glow Face Cleanser",sku:"MOR-FACE-01",category:"Skincare",price:1900,cost:850,stock:10,reorder:3,active:true},
{id:"p5",name:"Lash Care Serum",sku:"MOR-LASH-01",category:"Lashes",price:2100,cost:1000,stock:6,reorder:2,active:true}
],services:[
{id:"s1",name:"Hair & Styling",duration:"60 min",price:0,active:true},
{id:"s2",name:"Braiding",duration:"120 min",price:0,active:true},
{id:"s3",name:"Nails",duration:"60 min",price:0,active:true},
{id:"s4",name:"Lashes",duration:"90 min",price:0,active:true},
{id:"s5",name:"Makeup",duration:"60 min",price:0,active:true},
{id:"s6",name:"Brows",duration:"30 min",price:0,active:true},
{id:"s7",name:"Facials & Skincare",duration:"60 min",price:0,active:true}
],sales:[],bookings:[],customers:[],expenses:[],staff:[],reviews:[],gallery:[]};
let db=load(),cart=[],lastReceipt=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function clone(x){return JSON.parse(JSON.stringify(x))}
function load(){try{const raw=localStorage.getItem(KEY);return raw?Object.assign(clone(START),JSON.parse(raw)):clone(START)}catch{return clone(START)}}
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function money(n){return "KSh "+Number(n||0).toLocaleString("en-KE",{minimumFractionDigits:0,maximumFractionDigits:2})}
function id(p){return p+"_"+Date.now().toString(36)+"_"+Math.random().toString(36).slice(2,6)}
function toast(t){const el=$("#toast");el.textContent=t;el.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove("show"),2500)}
function today(){return new Date().toISOString().slice(0,10)}
function session(){return localStorage.getItem(SESSION)==="1"}
function boot(){
  if(session()) showApp(); else $("#admin-login").hidden=false;
  $("#login-form").addEventListener("submit",e=>{e.preventDefault();const email=$("#login-email").value.trim().toLowerCase(),pass=$("#login-password").value;if(!email||!pass)return;const configured=localStorage.getItem("moraa_admin_email");if(configured&&email!==configured){$("#login-error").textContent="This email is not authorised for the owner workspace.";return}if(!configured)localStorage.setItem("moraa_admin_email",email);localStorage.setItem(SESSION,"1");showApp()});
  $("#logout").addEventListener("click",()=>{localStorage.removeItem(SESSION);location.reload()});
}
function showApp(){$("#admin-login").hidden=true;$("#admin-app").hidden=false;$("#today-label").textContent=new Date().toLocaleDateString("en-KE",{weekday:"short",day:"numeric",month:"short",year:"numeric"});bindNav();renderAll()}
function bindNav(){
  $$("#side-nav button").forEach(b=>b.onclick=()=>openView(b.dataset.view));
  $$("[data-view-jump]").forEach(b=>b.onclick=()=>openView(b.dataset.viewJump));
  $("#mobile-menu").onclick=()=>$(".sidebar").classList.toggle("open");
}
function openView(view){$$("#side-nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===view));$$(".view").forEach(v=>v.classList.toggle("active",v.id==="view-"+view));const b=$(`#side-nav button[data-view="${view}"]`);$("#view-title").textContent=b?.querySelector("span")?.textContent||"Dashboard";$(".sidebar").classList.remove("open");renderView(view)}
function renderAll(){renderDashboard();renderPOS();renderSales();renderProducts();renderInventory();renderBookings();renderCustomers();renderServices();renderExpenses();renderStaff();renderContent();renderReviews();renderGallery();renderSettings()}
function renderView(v){({dashboard:renderDashboard,pos:renderPOS,sales:renderSales,products:renderProducts,inventory:renderInventory,bookings:renderBookings,customers:renderCustomers,services:renderServices,expenses:renderExpenses,staff:renderStaff,content:renderContent,reviews:renderReviews,gallery:renderGallery,settings:renderSettings}[v]||renderDashboard)()}
function renderDashboard(){
 const ds=db.sales.filter(s=>s.date===today()),sum=ds.reduce((a,s)=>a+s.total,0),stock=db.products.reduce((a,p)=>a+Number(p.stock),0),low=db.products.filter(p=>p.stock<=p.reorder).length;
 $("#stat-sales").textContent=money(sum);$("#stat-orders").textContent=ds.length+" transaction"+(ds.length===1?"":"s");$("#stat-stock").textContent=stock;$("#stat-low").textContent=low+" low stock";$("#stat-bookings").textContent=db.bookings.filter(b=>b.status!=="Completed"&&b.status!=="Cancelled").length;$("#stat-customers").textContent=db.customers.length;
 $("#recent-sales").innerHTML=table(["Receipt","Customer","Total","Payment"],ds.slice(-6).reverse().map(s=>[s.receipt,s.customer,money(s.total),s.payment]));
 const bs=db.bookings.filter(b=>b.date===today()).slice(0,6);$("#dash-bookings").innerHTML=bs.length?bs.map(b=>`<div class="cart-line"><div><strong>${esc(b.name)}</strong><small>${esc(b.service)} · ${esc(b.time)}</small></div><span class="status">${esc(b.status)}</span></div>`).join(""):"<p class='muted'>No appointments recorded for today.</p>";
}
function table(headers,rows){if(!rows.length)return"<p class='muted'>Nothing here yet.</p>";return"<table class='table'><thead><tr>"+headers.map(h=>"<th>"+h+"</th>").join("")+"</tr></thead><tbody>"+rows.map(r=>"<tr>"+r.map(c=>"<td>"+c+"</td>").join("")+"</tr>").join("")+"</tbody></table>"}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function renderPOS(){
 const cats=[...new Set(db.products.map(p=>p.category))];$("#pos-category").innerHTML="<option value=''>All categories</option>"+cats.map(c=>`<option>${esc(c)}</option>`).join("");
 const draw=()=>{const q=$("#pos-search").value.toLowerCase(),cat=$("#pos-category").value;const ps=db.products.filter(p=>p.active&&p.stock>0&&(!q||p.name.toLowerCase().includes(q)||p.sku.toLowerCase().includes(q))&&(!cat||p.category===cat));$("#pos-products").innerHTML=ps.map(p=>`<button class="product-tile" data-add="${p.id}"><small>${esc(p.category)} · ${esc(p.sku)}</small><strong>${esc(p.name)}</strong><span class="price">${money(p.price)}</span><small>${p.stock} in stock</small></button>`).join("")||"<p class='muted'>No products match this search.</p>";$$("[data-add]").forEach(b=>b.onclick=()=>addCart(b.dataset.add));renderCart()};$("#pos-search").oninput=draw;$("#pos-category").onchange=draw;draw();
 $("#clear-cart").onclick=()=>{cart=[];renderCart()};$("#checkout").onclick=checkout;$("#print-last").onclick=()=>lastReceipt&&printReceipt(lastReceipt);
}
function addCart(pid){const p=db.products.find(x=>x.id===pid),line=cart.find(x=>x.id===pid);if(!p)return;if(line){if(line.qty>=p.stock)return toast("Not enough stock available.");line.qty++}else cart.push({id:pid,qty:1});renderCart()}
function renderCart(){const count=cart.reduce((a,x)=>a+x.qty,0);$("#cart-badge").textContent=count;$("#cart-count").textContent=count+" item"+(count===1?"":"s");const lines=$("#cart-lines");lines.innerHTML=cart.length?cart.map(x=>{const p=db.products.find(y=>y.id===x.id);return`<div class="cart-line"><div><strong>${esc(p.name)}</strong><small>${money(p.price)} each</small><div class="qty"><button data-dec="${x.id}">−</button><span>${x.qty}</span><button data-inc="${x.id}">+</button></div></div><strong>${money(p.price*x.qty)}</strong></div>`}).join(""):"<p class='muted'>Add products to start a sale.</p>";$$("[data-inc]").forEach(b=>b.onclick=()=>changeQty(b.dataset.inc,1));$$("[data-dec]").forEach(b=>b.onclick=()=>changeQty(b.dataset.dec,-1));const sub=cart.reduce((a,x)=>{const p=db.products.find(y=>y.id===x.id);return a+p.price*x.qty},0),disc=Math.min(sub,Number($("#sale-discount")?.value||0));$("#cart-subtotal").textContent=money(sub);$("#cart-discount").textContent=money(disc);$("#cart-total").textContent=money(sub-disc)}
function changeQty(pid,d){const l=cart.find(x=>x.id===pid),p=db.products.find(x=>x.id===pid);if(!l)return;l.qty+=d;if(l.qty<=0)cart=cart.filter(x=>x.id!==pid);if(p&&l.qty>p.stock)l.qty=p.stock;renderCart()}
function checkout(){if(!cart.length)return toast("Add at least one product.");const sub=cart.reduce((a,x)=>a+db.products.find(p=>p.id===x.id).price*x.qty,0),disc=Math.min(sub,Number($("#sale-discount").value||0)),total=sub-disc,customer=$("#sale-customer").value.trim()||"Walk-in customer",payment=$("#sale-payment").value;cart.forEach(x=>{const p=db.products.find(y=>y.id===x.id);p.stock-=x.qty});const sale={id:id("sale"),receipt:"MR-"+Date.now().toString().slice(-8),date:today(),time:new Date().toLocaleTimeString("en-KE",{hour:"2-digit",minute:"2-digit"}),customer,payment,subtotal:sub,discount:disc,total,items:cart.map(x=>{const p=db.products.find(y=>y.id===x.id);return{name:p.name,sku:p.sku,qty:x.qty,price:p.price}})};db.sales.push(sale);const c=db.customers.find(x=>x.phone&&x.phone===$("#sale-customer").val().trim());if(c){c.visits=(c.visits||0)+1;c.lastVisit=today()}save();lastReceipt=sale;cart=[];$("#sale-customer").value="";$("#sale-discount").value=0;renderAll();toast("Sale completed · "+sale.receipt);printReceipt(sale)}
function printReceipt(s){const w=window.open("","_blank","width=420,height=700");if(!w)return;w.document.write(`<!doctype html><title>${s.receipt} | Moraa</title><style>body{font:14px Arial;padding:24px;color:#241710}h1{font:24px Georgia;margin:0 0 4px}.muted{color:#766a60}.line{display:flex;justify-content:space-between;border-bottom:1px dashed #ccc;padding:9px 0}.total{font-size:19px;font-weight:bold;padding-top:14px}</style><h1>Moraa Beauty Parlour</h1><div class="muted">${s.receipt} · ${s.date} ${s.time}</div><p>Customer: ${esc(s.customer)}<br>Payment: ${esc(s.payment)}</p>${s.items.map(i=>`<div class="line"><span>${esc(i.name)} × ${i.qty}</span><strong>${money(i.qty*i.price)}</strong></div>`).join("")}<div class="line"><span>Subtotal</span><strong>${money(s.subtotal)}</strong></div><div class="line"><span>Discount</span><strong>-${money(s.discount)}</strong></div><div class="line total"><span>Total</span><strong>${money(s.total)}</strong></div><p class="muted">Thank you for choosing Moraa.</p><script>window.onload=()=>window.print()<\/script>`);w.document.close()}
function renderSales(){const rows=db.sales.slice().reverse().map(s=>[`<strong>${s.receipt}</strong><br><small>${s.date} ${s.time}</small>`,esc(s.customer),money(s.total),esc(s.payment),`<button class="mini" data-receipt="${s.id}">Receipt</button>`]);$("#sales-table").innerHTML=table(["Receipt","Customer","Total","Payment",""],rows);$$("[data-receipt]").forEach(b=>b.onclick=()=>printReceipt(db.sales.find(s=>s.id===b.dataset.receipt)))}
function renderProducts(){const rows=db.products.map(p=>[`<strong>${esc(p.name)}</strong><br><small>${esc(p.sku)}</small>`,esc(p.category),money(p.price),p.stock,`<span class="status ${p.stock<=p.reorder?"red":"green"}">${p.stock<=p.reorder?"Low":"Healthy"}</span>`,`<button class="mini" data-edit-product="${p.id}">Edit</button> <button class="mini" data-delete-product="${p.id}">Delete</button>`]);$("#products-table").innerHTML=table(["Product","Category","Price","Stock","Status",""],rows);$$("[data-edit-product]").forEach(b=>b.onclick=()=>productModal(db.products.find(p=>p.id===b.dataset.editProduct)));$$("[data-delete-product]").forEach(b=>b.onclick=()=>{if(confirm("Delete this product?")){db.products=db.products.filter(p=>p.id!==b.dataset.deleteProduct);save();renderAll()}})}
function renderInventory(){const rows=db.products.map(p=>[`<strong>${esc(p.name)}</strong><br><small>${esc(p.sku)}</small>`,p.stock,p.reorder,money(p.cost*p.stock),`<button class="mini" data-stock="${p.id}">Adjust</button>`]);$("#inventory-table").innerHTML=table(["Product","On hand","Reorder at","Stock value",""],rows);$$("[data-stock]").forEach(b=>b.onclick=()=>stockModal(db.products.find(p=>p.id===b.dataset.stock)))}
function renderBookings(){const rows=db.bookings.slice().sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(b=>[`<strong>${esc(b.name)}</strong><br><small>${esc(b.phone)}</small>`,esc(b.service),esc(b.date)+" "+esc(b.time),`<span class="status">${esc(b.status)}</span>`,`<button class="mini" data-book-status="${b.id}">Update</button>`]);$("#bookings-table").innerHTML=table(["Client","Service","When","Status",""],rows);$("[data-book-status]").forEach(b=>b.onclick=()=>bookingStatus(b.dataset.bookStatus))}
function renderCustomers(){const rows=db.customers.map(c=>[`<strong>${esc(c.name)}</strong><br><small>${esc(c.phone)}</small>`,esc(c.email||"—"),c.visits||0,esc(c.lastVisit||"—"),`<button class="mini" data-edit-customer="${c.id}">Edit</button>`]);$("#customers-table").innerHTML=table(["Customer","Email","Visits","Last visit",""],rows);$$("[data-edit-customer]").forEach(b=>customerModal(db.customers.find(c=>c.id===b.dataset.editCustomer)))}
function renderServices(){const rows=db.services.map(s=>[`<strong>${esc(s.name)}</strong>`,esc(s.duration),s.price?money(s.price):"Contact us",`<span class="status ${s.active?"green":"red"}">${s.active?"Visible":"Hidden"}</span>`,`<button class="mini" data-edit-service="${s.id}">Edit</button>`]);$("#services-table").innerHTML=table(["Service","Duration","Price","Status",""],rows);$$("[data-edit-service]").forEach(b=>serviceModal(db.services.find(s=>s.id===b.dataset.editService)))}
function renderExpenses(){const rows=db.expenses.slice().reverse().map(e=>[esc(e.date),`<strong>${esc(e.description)}</strong>`,esc(e.category),money(e.amount),`<button class="mini" data-del-expense="${e.id}">Delete</button>`]);$("#expenses-table").innerHTML=table(["Date","Description","Category","Amount",""],rows);$$("[data-del-expense]").forEach(b=>b.onclick=()=>{db.expenses=db.expenses.filter(e=>e.id!==b.dataset.delExpense);save();renderExpenses()})}
function renderStaff(){const rows=db.staff.map(s=>[`<strong>${esc(s.name)}</strong>`,esc(s.role),esc(s.phone||"—"),`<span class="status ${s.active?"green":"red"}">${s.active?"Active":"Inactive"}</span>`,`<button class="mini" data-edit-staff="${s.id}">Edit</button>`]);$("#staff-table").innerHTML=table(["Name","Role","Phone","Status",""],rows);$$("[data-edit-staff]").forEach(b=>staffModal(db.staff.find(s=>s.id===b.dataset.editStaff)))}
function renderContent(){Object.entries(db.settings).forEach(([k,v])=>{const el=$(\`[data-setting="${k}"]\`);if(el)el.value=v||""})}
function renderReviews(){const rows=db.reviews.map(r=>[`<strong>${esc(r.name)}</strong>`,esc(r.text),r.rating+"/5",`<span class="status ${r.approved?"green":"red"}">${r.approved?"Published":"Hidden"}</span>`,`<button class="mini" data-review="${r.id}">${r.approved?"Hide":"Approve"}</button>`]);$("#reviews-table").innerHTML=table(["Client","Review","Rating","Status",""],rows);$$("[data-review]").forEach(b=>b.onclick=()=>{const r=db.reviews.find(x=>x.id===b.dataset.review);r.approved=!r.approved;save();renderReviews()})}
function renderGallery(){const rows=db.gallery.map(g=>[`<strong>${esc(g.title)}</strong>`,`<small>${esc(g.url)}</small>`,`<span class="status ${g.active?"green":"red"}">${g.active?"Visible":"Hidden"}</span>`,`<button class="mini" data-gallery="${g.id}">${g.active?"Hide":"Show"}</button> <button class="mini" data-gallery-del="${g.id}">Delete</button>`]);$("#gallery-table").innerHTML=table(["Title","Image URL","Status",""],rows);$$("[data-gallery]").forEach(b=>b.onclick=()=>{const g=db.gallery.find(x=>x.id===b.dataset.gallery);g.active=!g.active;save();renderGallery()});$$("[data-gallery-del]").forEach(b=>b.onclick=()=>{db.gallery=db.gallery.filter(x=>x.id!==b.dataset.galleryDel);save();renderGallery()})}
function renderSettings(){$("#admin-email-setting").value=localStorage.getItem("moraa_admin_email")||""}
function modal(title,body,submit){$("#modal-root").innerHTML=`<div class="modal-backdrop"><div class="modal"><h3>${title}</h3><form class="modal-form" id="modal-form">${body}<div class="modal-actions"><button type="button" class="ghost" id="modal-cancel">Cancel</button><button class="primary" type="submit">Save</button></div></form></div></div>`;$("#modal-cancel").onclick=()=>$("#modal-root").innerHTML="";$("#modal-form").onsubmit=e=>{e.preventDefault();submit(new FormData(e.target));$("#modal-root").innerHTML=""}}
function productModal(p={id:"",name:"",sku:"",category:"Hair Care",price:0,cost:0,stock:0,reorder:3,active:true}){modal(p.id?"Edit product":"Add product",`<label>Name<input name="name" required value="${esc(p.name)}"></label><label>SKU<input name="sku" required value="${esc(p.sku)}"></label><label>Category<input name="category" required value="${esc(p.category)}"></label><label>Selling price<input name="price" type="number" min="0" required value="${p.price}"></label><label>Cost price<input name="cost" type="number" min="0" required value="${p.cost}"></label><label>Stock<input name="stock" type="number" min="0" required value="${p.stock}"></label><label>Reorder level<input name="reorder" type="number" min="0" required value="${p.reorder}"></label><label>Visible in POS<select name="active"><option value="true" ${p.active?"selected":""}>Yes</option><option value="false" ${!p.active?"selected":""}>No</option></select></label>`,f=>{Object.assign(p,{name:f.get("name"),sku:f.get("sku"),category:f.get("category"),price:+f.get("price"),cost:+f.get("cost"),stock:+f.get("stock"),reorder:+f.get("reorder"),active:f.get("active")==="true"});if(!p.id){p.id=id("p");db.products.push(p)}save();renderAll();toast("Product saved")})}
function stockModal(p){modal("Adjust stock",`<p class="muted">${esc(p.name)} · current stock: <strong>${p.stock}</strong></p><label>Adjustment<input name="adjust" type="number" required placeholder="e.g. 5 or -2"></label><label>Reason<input name="reason" required placeholder="Stock count, delivery, damaged…"></label>`,f=>{p.stock=Math.max(0,p.stock+Number(f.get("adjust")));save();renderAll();toast("Stock updated")})}
function customerModal(c={id:"",name:"",phone:"",email:"",visits:0,lastVisit:""}){modal(c.id?"Edit customer":"Add customer",`<label>Name<input name="name" required value="${esc(c.name)}"></label><label>Phone<input name="phone" required value="${esc(c.phone)}"></label><label>Email<input name="email" type="email" value="${esc(c.email)}"></label>`,f=>{Object.assign(c,{name:f.get("name"),phone:f.get("phone"),email:f.get("email")});if(!c.id){c.id=id("c");db.customers.push(c)}save();renderCustomers();renderDashboard();toast("Customer saved")})}
function serviceModal(s={id:"",name:"",duration:"60 min",price:0,active:true}){modal(s.id?"Edit service":"Add service",`<label>Service name<input name="name" required value="${esc(s.name)}"></label><label>Duration<input name="duration" required value="${esc(s.duration)}"></label><label>Price (optional)<input name="price" type="number" min="0" value="${s.price}"></label><label>Visible<select name="active"><option value="true" ${s.active?"selected":""}>Yes</option><option value="false" ${!s.active?"selected":""}>No</option></select></label>`,f=>{Object.assign(s,{name:f.get("name"),duration:f.get("duration"),price:+f.get("price"),active:f.get("active")==="true"});if(!s.id){s.id=id("s");db.services.push(s)}save();renderServices();toast("Service saved")})}
function expenseModal(){modal("Add expense",`<label>Date<input name="date" type="date" value="${today()}" required></label><label>Description<input name="description" required></label><label>Category<input name="category" placeholder="Supplies, rent, utilities…" required></label><label>Amount<input name="amount" type="number" min="0" required></label>`,f=>{db.expenses.push({id:id("e"),date:f.get("date"),description:f.get("description"),category:f.get("category"),amount:+f.get("amount")});save();renderExpenses();toast("Expense recorded")})}
function staffModal(s={id:"",name:"",role:"Stylist",phone:"",active:true}){modal(s.id?"Edit staff":"Add staff",`<label>Name<input name="name" required value="${esc(s.name)}"></label><label>Role<input name="role" required value="${esc(s.role)}"></label><label>Phone<input name="phone" value="${esc(s.phone)}"></label><label>Active<select name="active"><option value="true" ${s.active?"selected":""}>Active</option><option value="false" ${!s.active?"selected":""}>Inactive</option></select></label>`,f=>{Object.assign(s,{name:f.get("name"),role:f.get("role"),phone:f.get("phone"),active:f.get("active")==="true"});if(!s.id){s.id=id("st");db.staff.push(s)}save();renderStaff();toast("Staff saved")})}
function reviewModal(){modal("Add review",`<label>Client name<input name="name" required></label><label>Rating<select name="rating"><option>5</option><option>4</option><option>3</option><option>2</option><option>1</option></select></label><label>Review<textarea name="text" required></textarea></label>`,f=>{db.reviews.push({id:id("r"),name:f.get("name"),rating:+f.get("rating"),text:f.get("text"),approved:false});save();renderReviews();toast("Review saved as hidden")})}
function galleryModal(){modal("Add gallery image",`<label>Title<input name="title" required></label><label>Image URL<input name="url" type="url" required placeholder="https://…"></label>`,f=>{db.gallery.push({id:id("g"),title:f.get("title"),url:f.get("url"),active:false});save();renderGallery();toast("Gallery image saved as hidden")})}
function bookingStatus(id){const b=db.bookings.find(x=>x.id===id);if(!b)return;const next={Pending:"Confirmed",Confirmed:"Completed",Completed:"Cancelled",Cancelled:"Pending"}[b.status]||"Pending";b.status=next;save();renderBookings();renderDashboard();toast("Booking status: "+next)}
function wire(){
 $("#add-product").onclick=()=>productModal();$("#stock-adjust").onclick=()=>db.products[0]&&stockModal(db.products[0]);$("#add-customer").onclick=()=>customerModal();$("#add-service").onclick=()=>serviceModal();$("#add-expense").onclick=expenseModal;$("#add-staff").onclick=()=>staffModal();$("#add-review").onclick=reviewModal;$("#add-gallery").onclick=galleryModal;
 $$("[data-book-status]").forEach(b=>b.onclick=()=>bookingStatus(b.dataset.bookStatus));
 $("#sale-discount").oninput=renderCart;
 $("#save-content").onclick=()=>{ $$("#view-content [data-setting]").forEach(el=>db.settings[el.dataset.setting]=el.value);save();toast("Website settings saved")};
 $("#save-admin-email").onclick=()=>{const e=$("#admin-email-setting").value.trim().toLowerCase();if(!e)return toast("Enter an admin email.");localStorage.setItem("moraa_admin_email",e);toast("Admin email saved")};
 $("#export-data").onclick=()=>download("moraa-backup-"+today()+".json",JSON.stringify(db,null,2),"application/json");
 $("#import-data").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{db=Object.assign(clone(START),JSON.parse(r.result));save();renderAll();toast("Backup restored")}catch{toast("Invalid backup file")}};r.readAsText(f)};
 $("#reset-data").onclick=()=>{if(confirm("Reset all Moraa admin data on this browser?")){db=clone(START);save();renderAll();toast("Workspace reset")}};
 $("#export-sales").onclick=()=>{const rows=[["Receipt","Date","Time","Customer","Payment","Subtotal","Discount","Total"],...db.sales.map(s=>[s.receipt,s.date,s.time,s.customer,s.payment,s.subtotal,s.discount,s.total])];download("moraa-sales-"+today()+".csv",rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(",")).join("\n"),"text/csv")};
}
function download(name,data,type){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
document.addEventListener("DOMContentLoaded",()=>{boot();wire()});
})();